#!/bin/bash
./md2strapdownhtml.sh dsc.md 'Direct Signal Control'
./md2strapdownhtml.sh index.md 'mriphysics.github.io'
./md2strapdownhtml.sh rfpulsedes.md 'rf pulse design'
./md2strapdownhtml.sh emsims.md 'electromagnetic simulations'
./md2strapdownhtml.sh fieldmapping.md 'fieldmapping'
./md2strapdownhtml.sh teaching.md 'teaching'
./md2strapdownhtml.sh teaching-mri-intro.md 'Masters: medical imaging sciences'
./md2strapdownhtml.sh teaching-rf-pulses.md 'Masters: advanced physics of MRI'
./md2strapdownhtml.sh teaching-sequence-sims.md 'Masters: advanced physics of MRI'
./md2strapdownhtml.sh teaching-antennas.md 'BEng: electrical engineering II'
